-- Additive persisted index-key premise for bounded native R3 readers.
-- Existing malformed rows refuse the entire migration before any new promise.
CREATE TEMP TABLE r3_reader_bound_check (ok INTEGER NOT NULL CHECK(ok=1)) STRICT;
INSERT INTO r3_reader_bound_check SELECT CASE WHEN EXISTS(SELECT 1 FROM r3_objects WHERE kind NOT IN ('ENROLLMENT','ENROLL_PREPARATION','ROUND_PREPARATION','GRANT','CLAIM','RECEIPT','ALIAS','RETURNED_UNUSED','RETIREMENT','RECONCILIATION','INSTALLATION','ORIGINAL_BASE','AUTHORITY','BEGIN','SEAL','TERMINAL')) THEN 0 ELSE 1 END;
INSERT INTO r3_reader_bound_check SELECT CASE WHEN EXISTS(SELECT 1 FROM r3_object_pages WHERE kind NOT IN ('ENROLLMENT','ENROLL_PREPARATION','ROUND_PREPARATION','GRANT','CLAIM','RECEIPT','ALIAS','RETURNED_UNUSED','RETIREMENT','RECONCILIATION','INSTALLATION','ORIGINAL_BASE','AUTHORITY','BEGIN','SEAL','TERMINAL')) THEN 0 ELSE 1 END;
DROP TABLE r3_reader_bound_check;
CREATE TRIGGER r3_objects_bounded_kind BEFORE INSERT ON r3_objects WHEN NEW.kind NOT IN ('ENROLLMENT','ENROLL_PREPARATION','ROUND_PREPARATION','GRANT','CLAIM','RECEIPT','ALIAS','RETURNED_UNUSED','RETIREMENT','RECONCILIATION','INSTALLATION','ORIGINAL_BASE','AUTHORITY','BEGIN','SEAL','TERMINAL') BEGIN SELECT RAISE(ABORT,'unbounded R3 fact kind'); END;
CREATE TRIGGER r3_object_pages_bounded_kind BEFORE INSERT ON r3_object_pages WHEN NEW.kind NOT IN ('ENROLLMENT','ENROLL_PREPARATION','ROUND_PREPARATION','GRANT','CLAIM','RECEIPT','ALIAS','RETURNED_UNUSED','RETIREMENT','RECONCILIATION','INSTALLATION','ORIGINAL_BASE','AUTHORITY','BEGIN','SEAL','TERMINAL') BEGIN SELECT RAISE(ABORT,'unbounded R3 fact kind'); END;
PRAGMA user_version=6;
